version: '3'
services:
    webserver:
        build: .
        depends_on:
            - mysql
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - /tmp:/tmp
            - ./:/var/www/html/url-shortener/
            - ./config/apache.conf:/etc/apache2/sites-enabled/000-default.conf

        entrypoint: "bash -c 'source /etc/apache2/envvars && /usr/sbin/apache2 -D FOREGROUND'"
    mysql:
        image: mysql:5.7.20
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=shortener
            - MYSQL_USER=root
        volumes:
            - /tmp:/tmp
            - ./data:/var/lib/mysql
            - ./db/init:/docker-entrypoint-initdb.d
